# Generated by Django 4.2.6 on 2024-06-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_in_stock',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=0),
        ),
    ]
